esphome:
  name: esp32-dev
  friendly_name: ESP32 Dev Board
  name_add_mac_suffix: True
  on_boot: 
    # Force GPIO18 LOW (Turns P-Channel MOSFET on)
    # Set priority such that this runs before i2c initialises
    - priority: 1200
      then:
        - lambda: |-
            gpio_config_t io_conf = {};
            io_conf.pin_bit_mask = (1ULL<<18);
            io_conf.mode = GPIO_MODE_OUTPUT;
            io_conf.pull_up_en = GPIO_PULLUP_DISABLE;
            io_conf.pull_down_en = GPIO_PULLDOWN_DISABLE;
            io_conf.intr_type = GPIO_INTR_DISABLE;
            gpio_config(&io_conf);
            gpio_set_level(GPIO_NUM_18, 0);

esp32:
  board: seeed_xiao_esp32c6
  framework:
    type: esp-idf

globals:
  - id: shtcx_done
    type: bool
    initial_value: "false"
  - id: bat_level_done
    type: bool
    initial_value: "false"
  - id: soil_done
    type: bool
    initial_value: "false"

external_components:
  - source:
      type: local
      path: .
    components: [ stemma_soil_sensor ]

#deep_sleep:
#  run_duration: 60s
#  sleep_duration: 0.5min
#  id: deep_sleep_ctrl

# Enable logging
logger:
#  level: INFO

# Enable Home Assistant API
api:

network:
  enable_ipv6: True

openthread:
  device_type: MTD
  tlv: !secret thread_tlv
#  poll_period: 60s

i2c:
  scl: GPIO23
  sda: GPIO22

sensor:
  - platform: shtcx
    id: shtcx_sensor
    update_interval: 10s
    temperature: 
      name: Temperatur
    humidity: 
      name: Luftfeuchte
      on_value: 
        then:
          - globals.set: 
              id: shtcx_done
              value: "true"
          - script.execute: check_all_done
  - platform: adc
    pin: GPIO2
    device_class: voltage
    name: Batteriespannung
    id: battery_voltage
    attenuation: 12db
    update_interval: 1s
    accuracy_decimals: 2
    entity_category: diagnostic
    filters: 
      - multiply: 2.0
      - median: 
          window_size: 5
          send_every: 5
          send_first_at: 3
    on_value: 
      then:
        - component.update: battery_level
  - platform: template
    name: Batterie
    id: battery_level
    device_class: battery
    unit_of_measurement: "%"
    lambda: "return id(battery_voltage).state;"
    update_interval: never
    accuracy_decimals: 0
    entity_category: diagnostic
    filters:
      - calibrate_polynomial: 
          degree: 3
          datapoints: 
            - 2.50 -> 0
            - 3.00 -> 2
            - 3.20 -> 7
            - 3.40 -> 20
            - 3.60 -> 45
            - 3.70 -> 58
            - 3.80 -> 70
            - 3.90 -> 80
            - 4.00 -> 88
            - 4.10 -> 95
            - 4.20 -> 100
      - clamp: 
          min_value: 0
          max_value: 100
    on_value: 
      then:
        - globals.set: 
            id: bat_level_done
            value: "true"
        - script.execute: check_all_done
  - platform: stemma_soil_sensor
    temperature:
      name: Bodentemperatur
    moisture:
      name: Bodenfeuchtigkeit
      unit_of_measurement: "%"
      filters:
        - calibrate_linear:
            - 200 -> 0    # Dry
            - 2000 -> 100  # Wet
        - lambda: |-
            if (x < 0.0) return 0.0;
            if (x > 100.0) return 100.0;
            return x;
      on_value: 
        then:
          - globals.set: 
              id: soil_done
              value: "true"
          - script.execute: check_all_done
    update_interval: 10s

script:
  - id: check_all_done
    then: 
      - logger.log: "Script: check_all_done"
      - if: 
          condition: 
            - all: 
                - lambda: "return id(shtcx_done);"
                - lambda: "return id(bat_level_done);"
                - lambda: "return id(soil_done);"
          then: 
#            - deep_sleep.enter: deep_sleep_ctrl
